//
//  FolioEngine.swift
//  Folio
//
//  Created by Tai Wong on 9/11/25.
//

import Foundation

public func mapPassagesToResults(_ passages: [RetrievedPassage], scoreFromBM25: (Double) -> Double = { $0 }) -> [RetrievedResult] {
    passages.map { p in
        RetrievedResult(
            sourceId: p.sourceId,
            startPage: p.startPage,
            excerpt: p.excerpt,
            text: p.text,
            bm25: p.bm25,
            cosine: nil,
            score: scoreFromBM25(p.bm25),
            citations: p.citations
        )
    }
}

public struct IndexingConfig: Sendable {
    public var useContextualPrefix = true
    public var contextFn: (@Sendable (_ doc: LoadedDocument, _ page: LoadedPage, _ chunk: String) async throws -> String)? = nil

    public init() {}
}

public struct FolioConfig {
    public var chunking = ChunkingConfig()
    public var indexing = IndexingConfig()
    public init() {}
}

public struct RetrievalFilter: Sendable, Hashable {
    public var sourceIds: Set<String>?
    public var fileTypes: Set<String>?
    public var pageRange: ClosedRange<Int>?
    public var tags: Set<String>?

    public init(sourceIds: Set<String>? = nil, fileTypes: Set<String>? = nil, pageRange: ClosedRange<Int>? = nil, tags: Set<String>? = nil) {
        self.sourceIds = sourceIds
        self.fileTypes = fileTypes
        self.pageRange = pageRange
        self.tags = tags
    }
}

public struct RetrievedPassage {
    public let sourceId: String
    public let startPage: Int?
    public let excerpt: String
    public let text: String
    public let bm25: Double
    public let citations: [Citation]
}

public struct RetrievedResult: Sendable {
    public let sourceId: String
    public let startPage: Int?
    public let excerpt: String
    public let text: String
    public let bm25: Double
    public let cosine: Double?
    public let score: Double
    public let citations: [Citation]
}

public struct Citation: Sendable, Hashable, Codable {
    public let sourceId: String
    public let sourceName: String
    public let fileType: String?
    public let page: Int?
    public let sectionTitle: String?
    public let chunkId: String
    public let parentId: String?
    public let excerpt: String?
}

/// Stored chunk exposed for debugging / inspection. Mirrors the internal store
/// row without leaking SQL-side types.
public struct InspectableChunk: Sendable, Hashable {
    public let chunkId: String
    public let page: Int?
    public let sectionTitle: String?
    public let text: String
    /// Contextual prefix generated by `IndexingConfig.contextFn` (or the
    /// rule-based fallback) and stored alongside the chunk. Empty when
    /// contextual prefixes are disabled. Prepended to `text` when computing
    /// FTS5 index content and embedding input, but kept separate on disk so
    /// the raw chunk content is preserved.
    public let contextPrefix: String

    public init(chunkId: String, page: Int?, sectionTitle: String?, text: String, contextPrefix: String = "") {
        self.chunkId = chunkId
        self.page = page
        self.sectionTitle = sectionTitle
        self.text = text
        self.contextPrefix = contextPrefix
    }
}

public struct DocumentFetch: Sendable {
    public let sourceId: String
    public let displayName: String
    public let startPage: Int?
    public let endPage: Int?
    public let text: String
    public let chunkIds: [String]
}

public final class FolioEngine {
    public static let defaultIndexId = "default"

    private let db: AppDatabase
    private let store:  DocChunkStore
    private let loaders: [DocumentLoader]
    private let chunker: Chunker
    private let embeddingProvider: EmbeddingProvider?
    private let textGenerator: TextGenerator?

    /// Default loader stack used when callers don't supply their own. Order
    /// matters: dispatch picks the first `supports(_:)` match. Single source of
    /// truth referenced by the three convenience initializers below.
    public static func defaultLoaders() -> [DocumentLoader] {
        [
            PDFDocumentLoader(),
            MarkdownDocumentLoader(),
            DOCXDocumentLoader(),
            HTMLDocumentLoader(),
            CSVDocumentLoader(),
            StructuredDataLoader(),
            ImageDocumentLoader(),
            TextDocumentLoader()
        ]
    }

    public convenience init(loaders: [DocumentLoader]? = nil, chunker: Chunker? = nil, embeddingProvider: EmbeddingProvider? = nil, textGenerator: TextGenerator? = nil) throws {
        let url = try FolioEngine.defaultDatabaseURL()
        let useLoaders = loaders ?? Self.defaultLoaders()
        let useChunker = chunker ?? UniversalChunker()

        try self.init(databaseURL: url, loaders: useLoaders, chunker: useChunker, embeddingProvider: embeddingProvider, textGenerator: textGenerator)
    }


    public convenience init(appGroup identifier: String, loaders: [DocumentLoader]? = nil, chunker: Chunker? = nil, embeddingProvider: EmbeddingProvider? = nil, textGenerator: TextGenerator? = nil) throws {
        let url = try FolioEngine.appGroupDatabaseURL(identifier: identifier)
        let useLoaders = loaders ?? Self.defaultLoaders()
        let useChunker = chunker ?? UniversalChunker()

        try self.init(databaseURL: url, loaders: useLoaders, chunker: useChunker, embeddingProvider: embeddingProvider, textGenerator: textGenerator)
    }

    /// Convenience: ingest the file at `url`, deriving `sourceId` from its last path
    /// component. Returns the derived id so callers can keep it around for follow-up
    /// queries / deletion. Loader is picked by UTI from the file extension; pass an
    /// explicit `sourceId` to override the derived value.
    @discardableResult
    public func ingest(url: URL, sourceId: String? = nil, config: FolioConfig = .init(), tags: Set<String>? = nil) throws -> String {
        let resolvedSourceId = sourceId ?? url.lastPathComponent
        let input = try Self.makeIngestInput(from: url)
        _ = try ingest(input, sourceId: resolvedSourceId, config: config, tags: tags)
        return resolvedSourceId
    }

    /// Convenience: ingest a plain-text blob with caller-provided `name` (used as both
    /// the display name and the derived `sourceId`).
    @discardableResult
    public func ingest(text: String, name: String, config: FolioConfig = .init(), tags: Set<String>? = nil) throws -> String {
        _ = try ingest(.text(text, name: name), sourceId: name, config: config, tags: tags)
        return name
    }

    /// Convenience: retrieve passages for `question` using whichever path is best given
    /// the engine's configuration. Hybrid (BM25 + cosine) when an embedding provider is
    /// configured, lexical-only otherwise. Returns `RetrievedResult` so callers see the
    /// same shape regardless of which retrieval ran.
    public func retrieve(_ question: String, in sourceId: String? = nil, filter: RetrievalFilter = .init(), limit: Int = 5, expand: Int = 1, expandToParent: Bool = false, mmr: MMRConfig? = nil) async throws -> [RetrievedResult] {
        let sanitized = Self.sanitizeForFTS(question)
        if embeddingProvider != nil {
            return try await searchHybrid(sanitized, in: sourceId, filter: filter, limit: limit, expand: expand, expandToParent: expandToParent, mmr: mmr)
        } else {
            let passages = try searchWithContext(sanitized, in: sourceId, filter: filter, limit: limit, expand: expand, expandToParent: expandToParent)
            return mapPassagesToResults(passages)
        }
    }

    /// Picks an `IngestInput` for a file URL by reading the data and tagging it with
    /// the best UTI we can infer from the path extension. Falls back to plain text for
    /// extensions we don't recognise so callers can still index miscellaneous notes.
    private static func makeIngestInput(from url: URL) throws -> IngestInput {
        let ext = url.pathExtension.lowercased()
        if ext == "pdf" { return .pdf(url) }

        let data = try Data(contentsOf: url)
        let uti: String?
        switch ext {
        case "txt", "log": uti = nil // route through .text path
        case "md", "markdown": uti = "public.markdown"
        case "docx": uti = "org.openxmlformats.wordprocessingml.document"
        case "html", "htm": uti = "public.html"
        case "rtf": uti = "public.rtf"
        case "csv": uti = "public.comma-separated-values-text"
        case "tsv": uti = "public.tab-separated-values-text"
        case "json": uti = "public.json"
        case "xml": uti = "public.xml"
        case "yaml", "yml": uti = "public.yaml"
        case "png": uti = "public.png"
        case "jpg", "jpeg": uti = "public.jpeg"
        case "heic", "heif": uti = "public.heic"
        case "tiff", "tif": uti = "public.tiff"
        case "gif": uti = "com.compuserve.gif"
        case "webp": uti = "org.webmproject.webp"
        default: uti = nil
        }

        if let uti {
            return .data(data, uti: uti, name: url.lastPathComponent)
        } else {
            let text = String(data: data, encoding: .utf8) ?? ""
            return .text(text, name: url.lastPathComponent)
        }
    }

    public static func inMemory(loaders: [DocumentLoader]? = nil, chunker: Chunker? = nil, embeddingProvider: EmbeddingProvider? = nil, textGenerator: TextGenerator? = nil) throws -> FolioEngine {
        let useLoaders = loaders ?? Self.defaultLoaders()
        let useChunker = chunker ?? UniversalChunker()

        return try FolioEngine(databaseURL: URL(fileURLWithPath: ":memory:"), loaders: useLoaders, chunker: useChunker, embeddingProvider: embeddingProvider, textGenerator: textGenerator)
    }

    public init(databaseURL: URL, loaders: [DocumentLoader], chunker: Chunker, embeddingProvider: EmbeddingProvider?, textGenerator: TextGenerator? = nil) throws {
        try FileManager.default.createDirectory(at: databaseURL.deletingLastPathComponent(), withIntermediateDirectories: true)

        self.db = try AppDatabase(path: databaseURL.path)
        self.store = DocChunkStore(dbQueue: db.dbQueue)
        self.loaders = loaders
        self.chunker = chunker
        self.embeddingProvider = embeddingProvider
        self.textGenerator = textGenerator
    }
    
    //Ingest any supported input with caller chosen sourceID
    @discardableResult
    public func ingest(_ input: IngestInput, sourceId: String, config: FolioConfig = .init(), tags: Set<String>? = nil) throws -> (pages: Int, chunks: Int) {
        guard let loader = loaders.first(where: { $0.supports(input) }) else {
            throw NSError(domain: "Folio", code: 400, userInfo: [NSLocalizedDescriptionKey: "No loader for input"])
        }
        
        let doc = try loader.load(input)
        let cleaned = HeaderFooterFilter.strip(doc)
        let metadata = sourceMetadata(for: input, document: doc)

        try? store.deleteChunks(forSourceId: sourceId)
        try? store.upsertSource(
            id: sourceId,
            filePath: metadata.filePath,
            displayName: metadata.displayName,
            url: metadata.url,
            uti: metadata.uti,
            fileType: metadata.fileType,
            pages: doc.pages.count,
            chunks: 0
        )

        let pieces = try chunker.chunk(sourceId: sourceId, doc: cleaned, config: config.chunking)

        
        var inserted = 0
        for c in pieces {
            
            let pg = c.page.flatMap { idx in cleaned.pages.first { $0.index == idx } } ?? cleaned.pages.first!
            let prefix = config.indexing.useContextualPrefix ? Contextualizer.prefix(doc: cleaned, page: pg, chunk: c.text) : ""
            
            let augmented = prefix + c.text
            
            try store.insert(
                chunkId: c.id,
                sourceId: c.sourceId,
                ordinal: c.ordinal,
                page: c.page,
                content: c.text,
                sectionTitle: c.sectionTitle,
                contextPrefix: prefix,
                parentId: c.parentId,
                contentHash: c.contentHash,
                ftsContent: augmented
            )
            
            inserted += 1
        }

        try? store.upsertSource(
            id: sourceId,
            filePath: metadata.filePath,
            displayName: metadata.displayName,
            url: metadata.url,
            uti: metadata.uti,
            fileType: metadata.fileType,
            pages: doc.pages.count,
            chunks: inserted
        )
        if let tags { try? store.replaceTags(forSourceId: sourceId, tags: tags) }

        return (doc.pages.count, inserted)
    }


    /// Async ingest with cooperative cancellation and optional progress reporting.
    ///
    /// `progress` (if supplied) fires with `.loading` after the loader returns, `.chunking`
    /// after chunking, then `.embedding` once per chunk. The task is checked for
    /// cancellation between each chunk and before each embedding call so callers can
    /// abort large documents without waiting for the loop to finish.
    @discardableResult
    public func ingestAsync(
        _ input: IngestInput,
        sourceId: String,
        config: FolioConfig = .init(),
        tags: Set<String>? = nil,
        progress: IngestProgressHandler? = nil
    ) async throws -> (pages: Int, chunks: Int) {

        guard let loader = loaders.first(where: { $0.supports(input) }) else {
            throw NSError(domain: "Folio", code: 400, userInfo: [NSLocalizedDescriptionKey: "No loader for input"])
        }

        try Task.checkCancellation()
        let doc = try loader.load(input)
        progress?(IngestProgress(phase: .loading, completed: doc.pages.count, total: doc.pages.count))

        try Task.checkCancellation()
        let cleaned = HeaderFooterFilter.strip(doc)
        let metadata = sourceMetadata(for: input, document: doc)

        try? store.deleteChunks(forSourceId: sourceId)
        try? store.upsertSource(
            id: sourceId,
            filePath: metadata.filePath,
            displayName: metadata.displayName,
            url: metadata.url,
            uti: metadata.uti,
            fileType: metadata.fileType,
            pages: doc.pages.count,
            chunks: 0
        )

        try Task.checkCancellation()
        let pieces = try chunker.chunk(sourceId: sourceId, doc: cleaned, config: config.chunking)
        progress?(IngestProgress(phase: .chunking, completed: pieces.count, total: pieces.count))

        var inserted = 0
        let total = pieces.count

        for c in pieces {
            try Task.checkCancellation()

            let pg = c.page.flatMap { idx in cleaned.pages.first { $0.index == idx } } ?? cleaned.pages.first!

            let key = store.cacheKey(sourceId: c.sourceId, page: c.page, chunk: c.text)
            var prefix = (try? store.getCachedPrefix(for: key)) ?? ""

            if config.indexing.useContextualPrefix && prefix.isEmpty {
                if let f = config.indexing.contextFn {
                    let raw = (try? await f(cleaned, pg, c.text)) ?? Contextualizer.prefix(doc: cleaned, page: pg, chunk: c.text)

                    var line = raw.replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespacesAndNewlines)
                    if line.count > 600 { line = String(line.prefix(600)) }
                    prefix = line.isEmpty ? Contextualizer.prefix(doc: cleaned, page: pg, chunk: c.text) : line

                    let meta = ["model": "user-provided", "rev": "v1", "chars": "\(prefix.count)"]
                    let metaJSON = (try? JSONSerialization.data(withJSONObject: meta)).flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
                    try? store.putCachedPrefix(key: key, value: prefix, metaJSON: metaJSON)
                } else {
                    prefix = Contextualizer.prefix(doc: cleaned, page: pg, chunk: c.text)
                }
            } else if !config.indexing.useContextualPrefix {
                prefix = ""
            }

            let augmented = prefix + c.text
            let newChunk = try store.insertReturningIdentifiers(
                chunkId: c.id,
                sourceId: c.sourceId,
                ordinal: c.ordinal,
                page: c.page,
                content: c.text,
                sectionTitle: c.sectionTitle,
                contextPrefix: prefix,
                parentId: c.parentId,
                contentHash: c.contentHash,
                ftsContent: augmented
            )

            inserted += 1
            if let embeddingProvider {
                try Task.checkCancellation()
                let vec = try await embeddingProvider.embed(augmented)
                try store.insertVector(
                    chunkId: newChunk.chunkId,
                    indexId: Self.defaultIndexId,
                    model: embeddingProvider.model,
                    vector: vec
                )
            }

            progress?(IngestProgress(phase: .embedding, completed: inserted, total: total))
        }

        try? store.upsertSource(
            id: sourceId,
            filePath: metadata.filePath,
            displayName: metadata.displayName,
            url: metadata.url,
            uti: metadata.uti,
            fileType: metadata.fileType,
            pages: doc.pages.count,
            chunks: inserted
        )
        if let tags { try? store.replaceTags(forSourceId: sourceId, tags: tags) }
        return (doc.pages.count, inserted)
    }

    /// Replaces the tags attached to a source. Pass an empty set to clear all tags.
    public func setTags(_ tags: Set<String>, forSource sourceId: String) throws {
        try store.replaceTags(forSourceId: sourceId, tags: tags)
    }

    /// Returns the tags attached to a source in ascending order.
    public func tags(forSource sourceId: String) throws -> [String] {
        try store.tags(forSourceId: sourceId)
    }

    @discardableResult
    public func searchWithContext(_ query: String, in sourceId: String? = nil, filter: RetrievalFilter = .init(), limit: Int = 5, expand: Int = 1, expandToParent: Bool = false) throws -> [RetrievedPassage] {
        precondition(limit > 0, "Limit needs to be greater than 0")
        precondition(expand >= 0, "Expand must be non-negative")

        let hits = try store.ftsHits(query: query, inSource: sourceId, filter: filter, limit: max(limit * 6, 60))

        var results: [RetrievedPassage] = []
        var usedRowids = Set<Int64>()

        for h in hits {
            guard !usedRowids.contains(h.rowid) else { continue }

            let window = try contextWindow(for: h, expand: expand, expandToParent: expandToParent)
            guard !window.isEmpty else { continue }

            window.forEach { usedRowids.insert($0.rowid) }

            let mergedText = window.map(\.text).joined(separator: "\n\n")
            let startPage = window.first?.page
            let citations = window.map {
                Citation(
                    sourceId: h.sourceId,
                    sourceName: h.sourceDisplayName,
                    fileType: h.sourceFileType,
                    page: $0.page,
                    sectionTitle: $0.sectionTitle,
                    chunkId: $0.chunkId,
                    parentId: $0.parentId,
                    excerpt: h.excerpt
                )
            }

            results.append(RetrievedPassage(sourceId: h.sourceId, startPage: startPage, excerpt: h.excerpt, text: mergedText, bm25: h.bm25, citations: citations))
            if results.count >= limit { break }

        }

        return results
    }

    /// Picks the chunks around a hit. If `expandToParent` is true and the hit's chunk
    /// declares a `parent_id`, returns every chunk under that parent — letting callers
    /// retrieve on a small chunk but answer with the larger surrounding section. Falls
    /// back to neighbor expansion when the chunk is parent-less.
    private func contextWindow(for hit: DocChunkStore.SnippetHit, expand: Int, expandToParent: Bool) throws -> [DocChunkStore.NeighborChunk] {
        if expandToParent, let parentId = hit.parentId {
            let parentChunks = try store.fetchChunksByParent(sourceId: hit.sourceId, parentId: parentId)
            if !parentChunks.isEmpty { return parentChunks }
        }
        return try store.fetchNeighbors(sourceId: hit.sourceId, around: hit.rowid, expand: expand)
    }

    public func fetchDocument(sourceId: String, startPage: Int? = nil, anchor: String? = nil, expand: Int = 2, maxChars: Int? = 8000) throws -> DocumentFetch {
        precondition(expand >= 0 && expand <= 8, "expand must be between 0 and 8")
        if let startPage {
            precondition(startPage >= 0, "startPage must be non-negative")
        }
        if let maxChars {
            precondition(maxChars > 0, "maxChars must be positive")
        }

        guard let source = try store.fetchSource(id: sourceId) else {
            throw NSError(domain: "Folio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Source not found"])
        }

        let trimmedAnchor = anchor?.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedAnchor = trimmedAnchor.flatMap { $0.isEmpty ? nil : $0 }
        let anchorRowId = try normalizedAnchor.flatMap { try store.findAnchorRowid(sourceId: sourceId, anchor: $0) }

        let chunks: [DocChunkStore.NeighborChunk]
        if let rowid = anchorRowId {
            chunks = try store.fetchNeighbors(sourceId: sourceId, around: rowid, expand: expand)
        } else if let startPage {
            chunks = try store.fetchChunks(forSourceId: sourceId, startingFromPage: startPage)
        } else {
            chunks = try store.fetchAllChunks(forSourceId: sourceId)
        }

        guard !chunks.isEmpty else {
            return DocumentFetch(sourceId: sourceId, displayName: source.displayName, startPage: nil, endPage: nil, text: "", chunkIds: [])
        }

        let chunkIds = chunks.map(\.chunkId)
        let startPage = chunks.compactMap(\.page).min()
        let endPage = chunks.compactMap(\.page).max()

        var text = chunks.map(\.text).joined(separator: "\n\n")
        if let maxChars, text.count > maxChars {
            text = String(text.prefix(maxChars))
        }

        return DocumentFetch(
            sourceId: sourceId,
            displayName: source.displayName,
            startPage: startPage,
            endPage: endPage,
            text: text,
            chunkIds: chunkIds
        )
    }

    /// Computes embeddings for any chunks that are missing a vector and persists them for hybrid search fusion.
    /// Keeping BM25 and cosine in sync is critical so both scorers see identical chunk sets.
    /// - Parameters:
    ///   - sourceId: Optionally scope the work to a specific source hierarchy.
    ///   - batch: The number of chunks to embed per API call.
    public func backfillEmbeddings(for sourceId: String? = nil, batch: Int = 64) async throws {
        guard let embeddingProvider else {
            throw NSError(domain: "Folio", code: 410, userInfo: [NSLocalizedDescriptionKey: "EmbeddingProvider not configured"])
        }
        precondition(batch > 0, "batch must be positive")

        while true {
            let chunks = try store.fetchEmbeddableChunks(for: sourceId, indexId: Self.defaultIndexId, limit: batch)
            if chunks.isEmpty { break }

            let textsToEmbed = chunks.map(\.embeddingText)
            let embeddings = try await embeddingProvider.embedBatch(textsToEmbed)
            guard embeddings.count == chunks.count else {
                throw NSError(domain: "Folio", code: 411, userInfo: [NSLocalizedDescriptionKey: "Embedding count mismatch"])
            }

            for (chunk, vector) in zip(chunks, embeddings) {
                try store.insertVector(
                    chunkId: chunk.chunkId,
                    indexId: Self.defaultIndexId,
                    model: embeddingProvider.model,
                    vector: vector
                )
            }
        }
    }

    public func searchHybrid(_ query: String, in sourceId: String? = nil, filter: RetrievalFilter = .init(), limit: Int = 5, expand: Int = 1, wBM25: Double = 0.5, expandToParent: Bool = false, mmr: MMRConfig? = nil) async throws -> [RetrievedResult] {
        precondition(limit > 0 && expand >= 0, "invalid params")

        let hits = try store.ftsHits(query: query, inSource: sourceId, filter: filter, limit: max(limit * 6, 60))
        if hits.isEmpty { return [] }

        var cosByRow: [Int64: Double] = [:]
        if let embeddingProvider {
            let qv = try await embeddingProvider.embed(query)
            let vrows = try store.fetchVectors(forRowids: hits.map { $0.rowid }, indexId: Self.defaultIndexId)
            
            func cosine(_ a: [Float], _ b: [Float]) -> Double {
                let n = min(a.count, b.count)
                var dot = 0.0, na = 0.0, nb = 0.0
                
                for i in 0..<n {
                    let x = Double(a[i]), y = Double(b[i])
                    dot += x*y
                    na += x*x
                    nb += y*y
                    
                }
                
                return (na == 0 || nb == 0) ? 0.0 : dot / (sqrt(na) * sqrt(nb))
            }
            
            for r in vrows {
                cosByRow[r.rowid] = cosine(qv, r.vec)
            }
        }
        
        let allBM = hits.map(\.bm25)

        struct Cand {
            let h: DocChunkStore.SnippetHit
            let fused: Double
            let cos: Double?
            let vec: [Float]?
        }

        var vectorByRow: [Int64: [Float]] = [:]
        if embeddingProvider != nil {
            let rows = try store.fetchVectors(forRowids: hits.map { $0.rowid }, indexId: Self.defaultIndexId)
            vectorByRow = Dictionary(uniqueKeysWithValues: rows.map { ($0.rowid, $0.vec) })
        }

        let fusionRanked = hits.map { h -> Cand in
            let cos = cosByRow[h.rowid]
            let fused = RankFusion.fuse(bm25: allBM, bm25: h.bm25, cosine: cos, wBM25: wBM25)
            return Cand(h: h, fused: fused, cos: cos, vec: vectorByRow[h.rowid])
        }.sorted { $0.fused > $1.fused }

        let ranked: [Cand]
        if let mmr {
            ranked = MMR.rerank(fusionRanked, lambda: mmr.lambda, k: mmr.k ?? limit, relevance: { $0.fused }, vector: { $0.vec })
        } else {
            ranked = fusionRanked
        }

        var out: [RetrievedResult] = []
        var used = Set<Int64>()

        for c in ranked {
            guard !used.contains(c.h.rowid) else {
                continue
            }

            let window = try contextWindow(for: c.h, expand: expand, expandToParent: expandToParent)
            guard !window.isEmpty else {
                continue
            }

            window.forEach { used.insert($0.rowid) }
            let citations = window.map {
                Citation(
                    sourceId: c.h.sourceId,
                    sourceName: c.h.sourceDisplayName,
                    fileType: c.h.sourceFileType,
                    page: $0.page,
                    sectionTitle: $0.sectionTitle,
                    chunkId: $0.chunkId,
                    parentId: $0.parentId,
                    excerpt: c.h.excerpt
                )
            }
            out.append(.init(sourceId: c.h.sourceId, startPage: window.first?.page, excerpt: c.h.excerpt, text: window.map(\.text).joined(separator: "\n\n"), bm25: c.h.bm25, cosine: c.cos, score: c.fused, citations: citations))

            if out.count >= limit {
                break
            }
        }

        return out
    }

    
    public func search(_ query: String, in sourceId: String? = nil, filter: RetrievalFilter = .init(), limit: Int = 10) throws -> [Snippet] {
        try store.ftsSnippets(query: query, inSource: sourceId, filter: filter, limit: limit)
    }

    /// Pure vector retrieval: cosine over every chunk in the configured embedding
    /// index, ignoring BM25 entirely. Useful for queries the lexical side can't help
    /// with (paraphrase, cross-lingual, "find documents about X" without keyword
    /// overlap). Throws if no embedding provider is configured.
    public func searchVectors(_ query: String, in sourceId: String? = nil, filter: RetrievalFilter = .init(), limit: Int = 5, expand: Int = 1, expandToParent: Bool = false, mmr: MMRConfig? = nil) async throws -> [RetrievedResult] {
        precondition(limit > 0 && expand >= 0, "invalid params")
        guard let embeddingProvider else {
            throw NSError(domain: "Folio", code: 412, userInfo: [NSLocalizedDescriptionKey: "searchVectors requires an EmbeddingProvider"])
        }

        let rows = try store.fetchAllVectorsWithChunks(indexId: Self.defaultIndexId, inSource: sourceId, filter: filter)
        if rows.isEmpty { return [] }

        let queryVec = try await embeddingProvider.embed(query)

        struct VCand {
            let row: DocChunkStore.VectorChunkRow
            let cosine: Double
        }

        let scored = rows.map { row -> VCand in
            VCand(row: row, cosine: Self.cosine(row.vector, queryVec))
        }.sorted { $0.cosine > $1.cosine }

        let ranked: [VCand]
        if let mmr {
            ranked = MMR.rerank(scored, lambda: mmr.lambda, k: mmr.k ?? limit, relevance: { $0.cosine }, vector: { $0.row.vector })
        } else {
            ranked = scored
        }

        var out: [RetrievedResult] = []
        var used = Set<Int64>()

        for c in ranked {
            guard !used.contains(c.row.rowid) else { continue }

            let hit = DocChunkStore.SnippetHit(
                rowid: c.row.rowid,
                chunkId: c.row.chunkId,
                sourceId: c.row.sourceId,
                sourceDisplayName: c.row.sourceDisplayName,
                sourceFileType: c.row.sourceFileType,
                page: c.row.page,
                sectionTitle: c.row.sectionTitle,
                parentId: c.row.parentId,
                excerpt: Self.synthesizeExcerpt(from: c.row.text),
                bm25: 0
            )

            let window = try contextWindow(for: hit, expand: expand, expandToParent: expandToParent)
            guard !window.isEmpty else { continue }

            window.forEach { used.insert($0.rowid) }

            let citations = window.map {
                Citation(
                    sourceId: hit.sourceId,
                    sourceName: hit.sourceDisplayName,
                    fileType: hit.sourceFileType,
                    page: $0.page,
                    sectionTitle: $0.sectionTitle,
                    chunkId: $0.chunkId,
                    parentId: $0.parentId,
                    excerpt: hit.excerpt
                )
            }

            out.append(RetrievedResult(
                sourceId: hit.sourceId,
                startPage: window.first?.page,
                excerpt: hit.excerpt,
                text: window.map(\.text).joined(separator: "\n\n"),
                bm25: 0,
                cosine: c.cosine,
                score: c.cosine,
                citations: citations
            ))

            if out.count >= limit { break }
        }

        return out
    }

    private static func cosine(_ a: [Float], _ b: [Float]) -> Double {
        let n = min(a.count, b.count)
        var dot = 0.0, na = 0.0, nb = 0.0
        for i in 0..<n {
            let x = Double(a[i]), y = Double(b[i])
            dot += x * y
            na += x * x
            nb += y * y
        }
        return (na == 0 || nb == 0) ? 0 : dot / (sqrt(na) * sqrt(nb))
    }

    private static func synthesizeExcerpt(from text: String, maxChars: Int = 200) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.count <= maxChars { return trimmed }
        return String(trimmed.prefix(maxChars)) + "…"
    }
    
    public func deleteSource(_ sourceId: String) throws {
        try store.deleteSource(id: sourceId)
    }

    /// Returns the model registered for the given embedding index, or `nil` if no vectors
    /// have been written to that index yet.
    public func embeddingIndexInfo(id: String = FolioEngine.defaultIndexId) throws -> EmbeddingModelInfo? {
        try store.fetchEmbeddingIndex(id: id)
    }
    
    public func listSources() throws -> [Source] {
        try store.listSources()
    }

    /// Returns every chunk stored for `sourceId` in ingestion order. Intended for
    /// demo / debugging surfaces (e.g. showing the user what the chunker produced
    /// for a particular document) — production retrieval should go through
    /// `search`, `searchWithContext`, or `searchHybrid` instead.
    public func chunks(forSourceId sourceId: String) throws -> [InspectableChunk] {
        try store.fetchAllChunks(forSourceId: sourceId).map { n in
            InspectableChunk(
                chunkId: n.chunkId,
                page: n.page,
                sectionTitle: n.sectionTitle,
                text: n.text,
                contextPrefix: n.contextPrefix
            )
        }
    }
    
    /// Retrieves relevant passages for `question`, builds a prompt with the configured
    /// `AnswerTemplate`, asks the configured `TextGenerator` to synthesise an answer,
    /// and returns the text along with citations resolved from any `[N]` markers the
    /// model emitted.
    ///
    /// Throws `Folio` error code 600 if no `TextGenerator` was supplied at engine
    /// construction.
    public func answer(
        _ question: String,
        in sourceId: String? = nil,
        filter: RetrievalFilter = .init(),
        limit: Int = 5,
        template: AnswerTemplate = .default,
        policy: AnswerPolicy = .default,
        temperature: Double? = 0.2,
        maxTokens: Int? = 1024
    ) async throws -> Answer {
        guard let generator = textGenerator else {
            throw NSError(
                domain: "Folio",
                code: 600,
                userInfo: [NSLocalizedDescriptionKey: "answer() requires a TextGenerator on the FolioEngine"]
            )
        }

        let searchQuery = FolioEngine.sanitizeForFTS(question)
        let passages = try await searchHybrid(searchQuery, in: sourceId, filter: filter, limit: limit)
        let messages = template.build(question, passages)
        let request = GenerationRequest(messages: messages, temperature: temperature, maxTokens: maxTokens)
        let text = try await generator.generate(request)
        let citations = resolveCitationMarkers(in: text, passages: passages)
        let confidence = computeAnswerConfidence(in: text, passages: passages)

        if shouldRefuseAnswer(text: text, citations: citations, confidence: confidence, passages: passages, policy: policy) {
            return Answer(text: policy.refusalText, citations: [], usedPassages: passages, confidence: 0)
        }

        return Answer(text: text, citations: citations, usedPassages: passages, confidence: confidence)
    }

    /// Streaming variant of `answer`. Emits the retrieved passages up front, then
    /// streams text fragments from the generator, then a final consolidated `Answer`.
    ///
    /// The function is `async throws` because retrieval is awaited before the stream
    /// is constructed; the returned stream only captures `Sendable` values.
    public func answerStream(
        _ question: String,
        in sourceId: String? = nil,
        filter: RetrievalFilter = .init(),
        limit: Int = 5,
        template: AnswerTemplate = .default,
        policy: AnswerPolicy = .default,
        temperature: Double? = 0.2,
        maxTokens: Int? = 1024
    ) async throws -> AsyncThrowingStream<AnswerStreamEvent, Error> {
        guard let generator = textGenerator else {
            throw NSError(
                domain: "Folio",
                code: 600,
                userInfo: [NSLocalizedDescriptionKey: "answerStream() requires a TextGenerator on the FolioEngine"]
            )
        }

        let searchQuery = FolioEngine.sanitizeForFTS(question)
        let passages = try await searchHybrid(searchQuery, in: sourceId, filter: filter, limit: limit)
        let messages = template.build(question, passages)
        let request = GenerationRequest(messages: messages, temperature: temperature, maxTokens: maxTokens)

        return AsyncThrowingStream { continuation in
            let task = Task {
                continuation.yield(.passages(passages))

                var accumulated = ""
                do {
                    for try await delta in generator.stream(request) {
                        if Task.isCancelled { break }
                        accumulated += delta
                        continuation.yield(.text(delta))
                    }
                } catch {
                    continuation.finish(throwing: error)
                    return
                }

                let citations = resolveCitationMarkers(in: accumulated, passages: passages)
                let confidence = computeAnswerConfidence(in: accumulated, passages: passages)
                let finalAnswer: Answer
                if shouldRefuseAnswer(text: accumulated, citations: citations, confidence: confidence, passages: passages, policy: policy) {
                    finalAnswer = Answer(text: policy.refusalText, citations: [], usedPassages: passages, confidence: 0)
                } else {
                    finalAnswer = Answer(text: accumulated, citations: citations, usedPassages: passages, confidence: confidence)
                }
                continuation.yield(.done(finalAnswer))
                continuation.finish()
            }

            continuation.onTermination = { _ in
                task.cancel()
            }
        }
    }

    /// Converts a natural-language question into an FTS5 `MATCH` expression that
    /// behaves usefully for question-answering.
    ///
    /// Two problems are addressed here:
    /// 1. FTS5's query parser rejects bare punctuation like `?` and `!`, so a
    ///    natural question like "what jumps over the dog?" otherwise crashes
    ///    retrieval. Non-alphanumerics are squashed to spaces.
    /// 2. FTS5's default operator is implicit AND, which is hostile to natural
    ///    questions — "what jumps over the dog" requires every word to appear,
    ///    and stop-words like "what" usually won't. Tokens are quoted and joined
    ///    with `OR` so partial overlap surfaces candidate chunks, leaving final
    ///    ranking to BM25 + vector fusion.
    ///
    /// Direct callers of `searchHybrid` / `search` still pass through FTS5
    /// unmodified, so power users keeping their own query DSL aren't affected.
    internal static func sanitizeForFTS(_ query: String) -> String {
        var cleaned = ""
        cleaned.reserveCapacity(query.count)
        for scalar in query.unicodeScalars {
            if CharacterSet.alphanumerics.contains(scalar) {
                cleaned.unicodeScalars.append(scalar)
            } else {
                cleaned.unicodeScalars.append(" ")
            }
        }
        let tokens = cleaned
            .split(separator: " ", omittingEmptySubsequences: true)
            .map(String.init)
        guard !tokens.isEmpty else { return "" }
        return tokens.map { "\"\($0)\"" }.joined(separator: " OR ")
    }

    internal static func defaultDatabaseURL() throws -> URL {
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = base.appendingPathComponent("Folio", isDirectory: true)
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        
        return dir.appendingPathComponent("folio.sqlite")
    }

    internal static func appGroupDatabaseURL(identifier: String) throws -> URL {
        let fm = FileManager.default
        
        guard let container = fm.containerURL(forSecurityApplicationGroupIdentifier: identifier) else {
            throw NSError(domain: "Folio", code: 401, userInfo: [NSLocalizedDescriptionKey: "App Group not found: \(identifier)"])
        }
        let dir = container.appendingPathComponent("Folio", isDirectory: true)
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        
        return dir.appendingPathComponent("folio.sqlite")
    }
}

private struct SourceMetadata {
    let filePath: String
    let displayName: String
    let url: String?
    let uti: String?
    let fileType: String?
}

private func sourceMetadata(for input: IngestInput, document: LoadedDocument) -> SourceMetadata {
    switch input {
    case .pdf(let url):
        return SourceMetadata(
            filePath: url.path,
            displayName: document.name,
            url: url.absoluteString,
            uti: "com.adobe.pdf",
            fileType: "pdf"
        )
    case .text(_, let name):
        return SourceMetadata(
            filePath: name ?? document.name,
            displayName: document.name,
            url: nil,
            uti: "public.plain-text",
            fileType: "text"
        )
    case .data(_, let uti, let name):
        let fileType: String
        if isMarkdownUTI(uti) {
            fileType = "markdown"
        } else if isDOCXUTI(uti) {
            fileType = "docx"
        } else if isImageUTI(uti) {
            fileType = "image"
        } else {
            fileType = uti.split(separator: ".").last.map(String.init) ?? "data"
        }

        return SourceMetadata(
            filePath: name ?? document.name,
            displayName: document.name,
            url: nil,
            uti: uti,
            fileType: fileType
        )
    }
}

private func isMarkdownUTI(_ uti: String) -> Bool {
    let normalized = uti.lowercased()
    return normalized == "net.daringfireball.markdown" || normalized == "public.markdown" || normalized == "public.md"
}

private func isDOCXUTI(_ uti: String) -> Bool {
    let normalized = uti.lowercased()
    return normalized == "org.openxmlformats.wordprocessingml.document" || normalized == "com.microsoft.word.docx"
}

private func isImageUTI(_ uti: String) -> Bool {
    let normalized = uti.lowercased()
    if normalized == "public.image" { return true }
    return ImageDocumentLoader.supportedUTIs.contains(normalized)
}
